#!/usr/bin/env php

<?php

use PHPackage\NewCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

$app = new Application('PHPackage', '0.1');

$app->add(new NewCommand);

$app->run();
