#!/usr/bin/env php

<?php

use PHPackage\NewCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('PHPackage', '0.1');

$app->add(new NewCommand);

$app->run();
